import math

a = 1.0
nl = 21

walls = []

natoms = 0
nbonds = 0
nangles = 0

atomtype = 2  # types of atom

mass = 1.00

for n1 in range(nl):
    for n2 in range(nl):
            wall = {}
            wall['id'] = natoms + 1
            wall['mole'] = 1
            wall['type'] = 1
            wall['x'] = n2 * a
            wall['y'] = n1 * a
            wall['z'] =1.0
            walls.append(wall)
            natoms += 1
del wall


with open('wall.data', 'w') as f:
    f.write("LAMMPS data file. CGCMM style. atom_style full generated by wangyu\n")
    f.write('\n')

    f.write(str(natoms) + ' atoms\n')
    f.write(str(atomtype) + ' atom types' + '\n')
    f.write('\n')

    f.write(str(-nl * a) + ' ' + str(nl * a) + ' ' + 'xlo xhi\n')
    f.write(str(-nl * a) + ' ' + str(nl * a) + ' ' + 'ylo yhi\n')
    f.write(str(-nl * a) + ' ' + str(nl * a) + ' ' + 'zlo zhi\n')
    f.write('\n')

    f.write('Masses\n')
    f.write('\n')
    for n in range(atomtype):
        f.write(str(n + 1) + ' ' + str(mass) + '\n')
    f.write('\n')

    f.write('Atoms # molecular\n')
    f.write('\n')
    for Atom in walls:
        f.write(str(Atom['id']) + ' ' + str(Atom['mole']) + ' ' + str(Atom['type']) + ' ' + str(Atom['x']) + ' ' + str(
            Atom['y']) + ' ' + str(Atom['z']) + '\n')
    f.write('\n')
