# coding=utf-8

N = 12
M = 20
natom = 0
ethylene = []  # 定义一个列表，保存单体信息（乙基）
polyethylene = []
# 读取单体
with open('ethylene.xyz', 'r') as f:
    lines = f.readlines()
    nline = 0
    for line in lines:
        atom = {}  # 定义一个字典，保存原子信息，包括原子种类,x,y,z(type、x、y、z)
        # 判断空行，用来判断结尾的空行
        if line == '\n':
            break
        nline += 1
        if nline < 3:
            continue
        line = line.strip()
        # print(line)
        arrline = line.split('\t')
        # print(len(arrline))
        # print(arrline)
        atom['element'] = arrline[0]
        atom['x'] = float(arrline[1])
        atom['y'] = float(arrline[2])
        atom['z'] = float(arrline[3])
        ethylene.append(atom)
'''
for atom_ in ethylene:
    print(atom_)
'''
# print(atom)
# print(ethylene)
# 设置单体的首端、尾端ethylene[0]['x']
'''
ethylene[0]是首端,ethylene[1]是尾端
'''

# 初始化坐标，(0,0,0)为起始点
offx = 0.0 - ethylene[1]['x']
offy = 0.0 - ethylene[1]['y']
offz = 0.0 - ethylene[1]['z']

for n in range(N):
    ethylene[n]['element'] = ethylene[n]['element']
    ethylene[n]['x'] = ethylene[n]['x'] + offx
    ethylene[n]['y'] = ethylene[n]['y'] + offy
    ethylene[n]['z'] = ethylene[n]['z'] + offz

# print(ethylene)
# 复制重复单元
for i in range(M):
    for j in range(N):
        atom = {}
        atom['element'] = ethylene[j]['element']
        atom['x'] = ethylene[j]['x'] + 5.2*i
        atom['y'] = ethylene[j]['y']
        atom['z'] = ethylene[j]['z']
        # print(atom)
        polyethylene.append(atom)
        natom += 1

# print(natom)

'''
for n in range(natom):
    print(polyethylene[n])
'''

# xyz文件导出
with open('polyethylene.xyz', 'w') as o:
    o.write(str(natom) + '\n')
    o.write('generated by wangyu\n')
    for atom in polyethylene:
        o.write(str(atom['element']) + ' ' + str(atom['x']) + ' ' + str(atom['y']) + ' ' + str(atom['z']) + '\n')
